_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "6": 4.46.1
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 64
data_dir:
    value: .data
device:
    value: cpu
learning_rate:
    value: 0.001
num_epochs:
    value: 20
save_dir:
    value: ./trained_models
seq_length:
    value: 4
train_split:
    value: 0.8
use_wandb:
    value: true
val_split:
    value: 0.2
weight_decay:
    value: 1e-05
