_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "6": 4.46.1
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 64
dropout:
    value: 0.1
epoch_out_freq:
    value: 1
epochs:
    value: 12
hf_repo:
    value: hiki-t/tf_model_mnist
lr:
    value: 0.0003
model_d:
    value: 128
num_heads:
    value: 2
num_layers:
    value: 2
num_patch:
    value: 64
patch_size:
    value: 7
